### ISSUE TITLE
Use ssh config file(s)

### ISSUE THREAD

**Issue by reynir** [fxfactorial/ocaml-libssh#5]
In some cases it can be necessary to pass in ssh options to connect to a server, for example because it's using otherwise disabled authentication methods. Calling `ssh_options_parse_config` with the file name as `NULL` will parse the default ssh config. The documentation says to call it as the last option. http://api.libssh.org/stable/group__libssh__session.html#ga82371e723260c7572ea061edecc2e9f1

I have a commit that implements this: https://github.com/reynir/ocaml-libssh/commit/f9eb557d80e30c4f0d74a7dd4e739a1668d6e7c1 I have only tested it against v0.1.

**Comment by fxfactorial** [comment]
Thanks for this, if you like I can give you commit access and you can commit directly to master to test out your ideas.

**Comment by reynir** [comment]
Hi, thanks. I'm not sure how much I will be poking at ocaml-libssh, to be honest :-) 

So, as described in #6 the cause of my issue might have been because of the port not being used and thus ocaml-libssh connecting to the wrong ssh server on the particular host. I will test tomorrow.
