### ISSUE TITLE
Port is never used

### ISSUE THREAD

**Issue by reynir** [fxfactorial/ocaml-libssh#6]
While re-reading the connect() code, I noticed the port is never used. This might have been the cause for the issues that caused me to raise issue #5. I will test tomorrow if using the port fixes my particular issue.

https://github.com/fxfactorial/ocaml-libssh/blob/master/src/libssh_stubs.c#L191

**Comment by fxfactorial** [comment]
Great, thanks for identifying that. I haven't touched these bindings in a bit so I appreciate your eyeballs.
